### ISSUE TITLE
Kafka 0.9.0.1 and Kafka Clients API for JDK 7

### ISSUE THREAD

**Issue by wojtek-szymanski** [charithe/kafka-junit#14]
Hi

It would be nice to have your recent changes you made in version 2.0 for JDK 7 too. I have a couple of projects using the latest Kafka version but still running on Java 7.

If you would be so kind and decide to release such version, please find changes in my repo on branch kafka-junit-1.9.1. I do not want to create PR to your master because of project version and JDK difference.

My branch:
https://github.com/wojtek-szymanski/kafka-junit/tree/kafka-junit-1.9.1

Commits:
https://github.com/wojtek-szymanski/kafka-junit/commit/74129bd9accbebc95fe17f90ecd2cca98f66d6e5
https://github.com/wojtek-szymanski/kafka-junit/commit/c76babab3ac5b8398a5f6e99fbb728a742506ff3

**Comment by charithe** [comment]
Hi,

Thanks for letting me know about your fork. I assumed it was fine to switch to Java 8 since Java 7 has been EOL for over an year now. May I ask what prevents you from switching to Java 8?

**Comment by wojtek-szymanski** [comment]
I think there are a couple of reasons for this, let me give you some context. Part of our tomcat micro services were created before java 8 release and there is no pressure to switch. Although from developers perspective switch is cool and easy, it looks a bit different for devops and finally business people who have different priorities. Another group of our apps is based on Hadoop stack, which in older distro versions do not support Java 8. So as you can see, switching to Java 8 will take some time and that's why allowing backward compatibility is still valid for many different use cases.

**Comment by charithe** [comment]
OK, fair enough. I have switched back to Java 7 and released version 2.1.

**Comment by wojtek-szymanski** [comment]
Many thanks, Charith.
