### ISSUE TITLE
Rule does not allow configuration of de/serializers

### ISSUE THREAD

**Issue by cjstehno** [charithe/kafka-junit#19]
Recently I ran into the need to apply configuration to the `StringDeserializer` and found two issues:
1. There is no way to provide additional producer/consumer configuration properties (other than building everything outside the Rule)
2. The `configure(Map,boolean)` methods are never called with the configuration during setup.

I ended up coding a simple extension in Groovy for our needs, but this would be a nice addition to the base functionality. Here is my extension:

``` groovy
class ExtendedKafkaJunitRule extends KafkaJunitRule {

    Properties consumerConfig(final Properties addedProps, final boolean autoConfig) {
        Properties config = consumerConfig(autoConfig)
        config.putAll(addedProps)
        config
    }

    public <K, V> KafkaConsumer<K, V> createConsumer(final Properties extraConfig, final Deserializer<K> keyDeser, final Deserializer<V> valDeser, final boolean autoCommit) {
        def config = consumerConfig(extraConfig, autoCommit)

        keyDeser.configure(config, true)
        valDeser.configure(config, false)

        new KafkaConsumer<K, V>(config, keyDeser, valDeser)
    }

    public <K, V> ListenableFuture<List<ConsumerRecord<K, V>>> pollMessages(Properties extraConfig, String topic, int numMessagesToPoll, Deserializer<K> keyDeserializer, Deserializer<V> valueDeserializer) {
        KafkaConsumer consumer = createConsumer(extraConfig, keyDeserializer, valueDeserializer, false)
        consumer.subscribe([topic])

        ListeningExecutorService executor = MoreExecutors.listeningDecorator(Executors.newSingleThreadExecutor())
        return executor.submit(new KafkaJunitRule.RecordConsumer(numMessagesToPoll, consumer))
    }

    public ListenableFuture<List<ConsumerRecord<String, String>>> pollStringMessages(Properties extraConfig, String topic, int numMessagesToPoll) {
        return pollMessages(extraConfig, topic, numMessagesToPoll, new StringDeserializer(), new StringDeserializer())
    }
}
```

I would be willing to add this to the base class myself (in Java) and create a pull request, if you are open to contributions.

**Comment by charithe** [comment]
Hi,

I am certainly open to contributions. In the case of overriding the consumer config, I have been a bit reluctant to add support for it because I intended the `pollMessages` method to be just a convenience method for quickly testing whether your producer code worked or not. If the test required more effort than that, I expected the users to write the appropriate consumer code themselves because I felt that it was a rare enough use case that did not warrant adding extra parameters and method overrides to the code.    

That being said, you're the second person to enquire about this. Can you tell me a little bit about your test scenario and what extra configuration properties are needed to make it work? 

Thanks

**Comment by cjstehno** [comment]
I ran into a case where I wanted to set the `value.deserializer.encoding` property and have it picked up by the `StringDeserializer` - I started out as you said, using the rule to create the basic configuration and then adding my new config to it, but then I realized that I would also have to create the consumer and the serializers (since they were not having configure called). 

I agree that my solution is not the most elegant, but it got the job done. Maybe if there were another easy way to provide extra consumer/producer config, even through the constructor.

**Comment by charithe** [comment]
That's a fair point. I'll think about it a little bit more and try to get something coded over the weekend. It'll probably be very similar to what you suggested anyway.

**Comment by charithe** [comment]
So I did some refactoring and now you can provide configuration overrides when creating producers and consumers.

```java
KafkaConsumer<String,String> consumer = kafkaRule.helper().createStringConsumer(overrideProps);
ListenableFuture<List<ConsumerRecord<String,String>>> records = kafkaRule.helper().consume(topic, consumer, numMessagesToConsume);
```
Version `3.0.0-SNAPSHOT` is now available on Sonatype snapshots. This version contains breaking API changes so please refer to the README for more information. I'll cut a release in a couple of days after a few more tweaks.

**Comment by cjstehno** [comment]
Great! I will check it out and give it a try soon. Thanks!

**Comment by charithe** [comment]
I am assuming that this issue has been resolved. Feel free to re-open if that's not the case.
