### ISSUE TITLE
Add support for Kafka version 0.10.2.0

### ISSUE THREAD

**Issue by mattyb678** [charithe/kafka-junit#23]
Add support for the latest Kafka version (0.10.2.0)

**Comment by pgracio** [comment]
Hi, I'm now using latest version of `kafka-junit:3.0.3` and `kafka-streams:0.10.2.0`. This is probably not a error related with kafka-junit but have you seen this exception?

`org.apache.kafka.streams.errors.StreamsException: Could not find any available broker.
`

**Comment by charithe** [comment]
I have not tried to use the Kafka rule with a Streams application so I don't know whether it's genuinely an issue with the way the temporary broker is spun up by the rule or whether it's an environmental issue on your end. Have you tried increasing the timeouts by overriding the broker properties on rule creation?

http://charithe.github.io/kafka-junit/com/github/charithe/kafka/EphemeralKafkaBroker.html#create-int-int-java.util.Properties-
