### ISSUE TITLE
java.lang.NoSuchFieldError: configFileStr

### ISSUE THREAD

**Issue by samuraraujo** [charithe/kafka-junit#28]
Any idea how to fix it? 

com.geophy.coredb.core.kafka.producer.StardogTxProducerTest
Exception in thread "Thread-1" java.lang.NoSuchFieldError: configFileStr
	at org.apache.curator.test.QuorumConfigBuilder$1.<init>(QuorumConfigBuilder.java:142)
	at org.apache.curator.test.QuorumConfigBuilder.buildConfig(QuorumConfigBuilder.java:137)
	at org.apache.curator.test.TestingZooKeeperServer$1.run(TestingZooKeeperServer.java:149)
	at java.lang.Thread.run(Thread.java:748)

java.lang.IllegalStateException: Timed out waiting for watch removal

	at org.apache.curator.test.TestingZooKeeperMain.blockUntilStarted(TestingZooKeeperMain.java:153)
	at org.apache.curator.test.TestingZooKeeperServer.start(TestingZooKeeperServer.java:159)
	at org.apache.curator.test.TestingServer.<init>(TestingServer.java:117)
	at org.apache.curator.test.TestingServer.<init>(TestingServer.java:100)
	at org.apache.curator.test.TestingServer.<init>(TestingServer.java:52)
	at com.github.charithe.kafka.EphemeralKafkaBroker.startBroker(EphemeralKafkaBroker.java:124)
	at com.github.charithe.kafka.EphemeralKafkaBroker.start(EphemeralKafkaBroker.java:114)
	at com.geophy.coredb.core.kafka.producer.StardogTxProducerTest.setup(StardogTxProducerTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

<dependency>
			<groupId>com.github.charithe</groupId>
			<artifactId>kafka-junit</artifactId>
			<version>3.0.3</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.12</artifactId>
            <version>0.10.2.0</version>
			<scope>compile</scope>

**Comment by samuraraujo** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.geophy.coredb.core</groupId>
	<artifactId>core-kafka</artifactId>
	<version>0.0.25-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>CoreDB Core Kafka</name>
	<url>http://maven.apache.org</url>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<java.version>1.8</java.version>
		<java.version.javadoc>http://java.sun.com/javase/8/docs/api/</java.version.javadoc>
		<file.encoding>UTF-8</file.encoding>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<slf4j-version>1.7.24</slf4j-version>
		<log4j-version>2.8.2</log4j-version>
		<jena-sparql-api-version>3.3.0-1</jena-sparql-api-version>
		<org-apache-jena-version>3.3.0</org-apache-jena-version>
	</properties>

	<scm>
		<url>scm:git:ssh://git@git.geophy.com:9922/coredb/coredb-core-kafka.git</url>
		<connection>scm:git:ssh://git@git.geophy.com:9922/coredb/coredb-core-kafka.git</connection>
	  <tag>HEAD</tag>
  	</scm>

	<prerequisites>
		<maven>3.0</maven>
	</prerequisites>


	<dependencies>
		<dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
			<version>2.3.2</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-cli</groupId>
                    <artifactId>commons-cli</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
		</dependency>

		
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1</version>
		</dependency>
		
		<dependency>
			<groupId>com.github.charithe</groupId>
			<artifactId>kafka-junit</artifactId>
			<version>3.0.3</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.12</artifactId>
            <version>0.10.2.0</version>
			<scope>compile</scope>
			<exclusions>
                <exclusion>
                    <artifactId>junit</artifactId>
                    <groupId>junit</groupId>
                </exclusion>
				<exclusion>
					<artifactId>jmxri</artifactId>
					<groupId>com.sun.jmx</groupId>
				</exclusion>
				<exclusion>
					<artifactId>jms</artifactId>
					<groupId>javax.jms</groupId>
				</exclusion>
				<exclusion>
					<artifactId>jmxtools</artifactId>
					<groupId>com.sun.jdmk</groupId>
				</exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
			</exclusions>
		</dependency>

		
		<dependency>
			<groupId>org.apache.jena</groupId>
			<artifactId>jena-arq</artifactId>
			<version>${org-apache-jena-version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.thrift</groupId>
					<artifactId>libthrift</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.apache.thrift</groupId>
			<artifactId>libthrift</artifactId>
			<version>0.9.3</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpclient</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpcore</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.apache.jena</groupId>
			<artifactId>jena-core</artifactId>
			<version>${org-apache-jena-version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-cli</groupId>
					<artifactId>commons-cli</artifactId>
				</exclusion>
			</exclusions>
		</dependency>


		
		<dependency>
			<groupId>com.geophy.coredb.core</groupId>
			<artifactId>core-utils-rdf</artifactId>
			<version>0.11</version>
		</dependency>

		
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>22.0</version>
		</dependency>


		
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>${log4j-version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>${log4j-version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-slf4j-impl</artifactId>
			<version>${log4j-version}</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4j-version}</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>

		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>3.8.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-all</artifactId>
			<version>1.10.19</version>
			<scope>test</scope>
		</dependency>

	</dependencies>
	<build>
		<plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.1</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
            <plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>appassembler-maven-plugin</artifactId>
				<version>2.0.0</version>
				<configuration>
					<extraJvmArguments>-Xms512M -Xmx2048M</extraJvmArguments>
					<programs>
						<program>
							<mainClass>com.geophy.coredb.core.kafka.producer.StardogTxProducer</mainClass>
							<name>stardog-producer</name>
						</program>

						<program>
							<mainClass>com.geophy.coredb.core.kafka.topicsdistributor.KafkaTopicsDistributorQuadsMsgs</mainClass>
							<name>KafkaTopicsDistributorQuadsMsgs</name>
						</program>

						<program>
							<mainClass>com.geophy.coredb.core.kafka.mozart.queryperformance.MeasureQueryPerformance</mainClass>
							<name>MeasureQueryPerformance</name>
						</program>

						<program>
							<mainClass>com.geophy.coredb.core.kafka.mozart.queryperformance.MeasureIterSelectQueryResults</mainClass>
							<name>MeasureIterSelectQueryResults</name>
						</program>

						<program>
							<mainClass>com.geophy.coredb.core.kafka.multitopics.MultiTopicsProducer</mainClass>
							<name>MultiTopicsProducer</name>
						</program>

						<program>
							<mainClass>com.geophy.coredb.core.kafka.multitopics.MultiTopicsConsumer</mainClass>
							<name>MultiTopicsConsumer</name>
						</program>

						<program>
							<mainClass>com.geophy.coredb.core.kafka.performance.OneMConsumer</mainClass>
							<name>OneMConsumer</name>
						</program>

					</programs>
				</configuration>
			</plugin>

            

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>2.5.3</version>
				<configuration>
					<goals>deploy</goals>
					<autoVersionSubmodules>true</autoVersionSubmodules>
					<useReleaseProfile>true</useReleaseProfile>
					<releaseProfiles>release</releaseProfiles>
					<tagNameFormat>v@{project.version}</tagNameFormat>
				</configuration>
			</plugin>


		</plugins>
	</build>


	<profiles>
		<profile>
			<id>release</id>
			<build>
				<plugins>

					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-source-plugin</artifactId>
						<version>3.0.1</version>
						<executions>
							<execution>
								<id>attach-sources</id>
								<phase>install</phase>
								<goals>
									<goal>jar</goal>
								</goals>
							</execution>
						</executions>
					</plugin>

					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-javadoc-plugin</artifactId>
						<version>2.10.4</version>
						<configuration>
							<defaultVersion>${project.version}</defaultVersion>
						</configuration>
						<executions>
							<execution>
								<id>attach-javadocs</id>
								<goals>
									<goal>jar</goal>
								</goals>
							</execution>
						</executions>
					</plugin>


				</plugins>
			</build>
		</profile>
		<profile>
			<id>assembly</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-assembly-plugin</artifactId>
						<version>3.0.0</version>
						<configuration>
							<archive>
								<manifest>
									<mainClass>com.geophy.coredb.core.kafka.producer.StardogTxProducer</mainClass>
								</manifest>
							</archive>
							<descriptorRefs>
								<descriptorRef>jar-with-dependencies</descriptorRef>
							</descriptorRefs>
						</configuration>
						<executions>
							<execution>
								<id>make-assembly</id> 
								<phase>package</phase> 
								<goals>
									<goal>single</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		
		<profile>
			<id>sonar-coverage</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<build>
				<pluginManagement>
					<plugins>
						<plugin>
							<groupId>org.jacoco</groupId>
							<artifactId>jacoco-maven-plugin</artifactId>
							<version>0.7.7.201606060606</version>
						</plugin>
					</plugins>
				</pluginManagement>
				<plugins>
					<plugin>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
						<configuration>
							<append>true</append>
						</configuration>
						<executions>
							<execution>
								<id>agent-for-ut</id>
								<goals>
									<goal>prepare-agent</goal>
								</goals>
							</execution>
							<execution>
								<id>agent-for-it</id>
								<goals>
									<goal>prepare-agent-integration</goal>
								</goals>
							</execution>
							<execution>
								<id>jacoco-site</id>
								<phase>verify</phase>
								<goals>
									<goal>report</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>enforcer</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-enforcer-plugin</artifactId>
						<version>1.4.1</version>
						<executions>
							<execution>
								<id>enforce</id>
								<configuration>
									<rules>
										<dependencyConvergence />
										<requireReleaseDeps>
											<message>No Snapshots Allowed!</message>
										</requireReleaseDeps>
									</rules>
								</configuration>
								<goals>
									<goal>enforce</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>


	</profiles>


	<repositories>
		<repository>
			<id>geophy-release</id>
			<name>Geophy Release Repository</name>
			<url>https://maven.geophy.com/repository/maven-releases/</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>

	<distributionManagement>
		<repository>
			<id>geophy-release</id>
			<name>Geophy Release Repository</name>
			<url>https://maven.geophy.com/repository/maven-releases/</url>
		</repository>
	</distributionManagement>

</project>

**Comment by charithe** [comment]
It sounds like one of your dependencies has a transitive dependency on a version of Curator that is conflicting with the version needed by kafka-junit. My advice is to look at `mvn dependency:tree` and add an exclusion rule to remove the older Curator version.

**Comment by nilsmagnus** [comment]
Probably the same solution as this issue: https://github.com/charithe/kafka-junit/issues/22 (wrong zookeeper version on test-classpath)
