### ISSUE TITLE
Does not work with dependency kafka-avro-serializer

### ISSUE THREAD

**Issue by simplesteph** [charithe/kafka-junit#29]
When you include 
```
       <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>kafka-avro-serializer</artifactId>
            <!-- For CP 3.3.0 -->
            <version>3.3.0</version>
        </dependency>
```

one gets
```
Exception in thread "Thread-0" java.lang.NoSuchFieldError: configFileStr
        at org.apache.curator.test.QuorumConfigBuilder$1.<init>(QuorumConfigBuilder.java:142)
        at org.apache.curator.test.QuorumConfigBuilder.buildConfig(QuorumConfigBuilder.java:137)
        at org.apache.curator.test.TestingZooKeeperServer$1.run(TestingZooKeeperServer.java:157)
        at java.lang.Thread.run(Thread.java:748)
```

Is it possible to get official guidance to make the two libraries co-exist?

**Comment by charithe** [comment]
It sounds like the Avro serializer library has a transitive dependency on Curator. Try adding an exclusion rule to the dependency declaration.

**Comment by simplesteph** [comment]
Do you have a working example? I'm not sure how to do that. I think that's something that should be documented on your front page as well because I'm sure other people will encounter that issue.

And I don't see Curator here unfortunately :(

```
mvn dependency:tree 
[INFO] +- io.confluent:kafka-avro-serializer:jar:3.3.0:compile
[INFO] |  +- org.apache.avro:avro:jar:1.8.2:compile
[INFO] |  |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  |  +- com.thoughtworks.paranamer:paranamer:jar:2.7:compile
[INFO] |  |  +- org.xerial.snappy:snappy-java:jar:1.1.1.3:compile
[INFO] |  |  +- org.apache.commons:commons-compress:jar:1.8.1:compile
[INFO] |  |  \- org.tukaani:xz:jar:1.5:compile
[INFO] |  +- io.confluent:kafka-schema-registry-client:jar:3.3.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.4:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.8.4:compile
[INFO] |  |  \- org.slf4j:slf4j-log4j12:jar:1.7.21:compile
[INFO] |  |     \- log4j:log4j:jar:1.2.17:compile
[INFO] |  +- io.confluent:common-config:jar:3.3.0:compile
[INFO] |  \- io.confluent:common-utils:jar:3.3.0:compile
[INFO] |     +- org.apache.zookeeper:zookeeper:jar:3.4.8:compile
[INFO] |     |  +- jline:jline:jar:0.9.94:compile
[INFO] |     |  \- io.netty:netty:jar:3.7.0.Final:compile
[INFO] |     \- com.101tec:zkclient:jar:0.10:compile
```

**Comment by simplesteph** [comment]
I think the issue is that you're targetting curator-test 4.0.0. This dependency is on Zookeeper 3.5.x, which is not the zookeeper supported by Kafka. 

Maybe try downgrading to `curator-test 2.12.0` ?

**Comment by charithe** [comment]
Ah, it must be the transitive dependency on Zookeeper. Try excluding that from the Avro dependency. 

```xml
<dependency>
    <groupId>io.confluent</groupId>
    <artifactId>kafka-avro-serializer</artifactId>
    <version>3.3.0</version>
    <exclusions>
         <exclusion>
             <groupId>org.apache</groupId>
             <artifactId>zookeeper</artifactId>
         </exclusion>
    </exclusions>
</dependency>
```

I'd rather not downgrade Curator now because it could cause a lot of existing code to break.

**Comment by simplesteph** [comment]
According to https://mvnrepository.com/artifact/org.apache.curator/curator-test
2.12 and 3.3.0 were both released in March 2017.
2.12 targets zookeeper 3.4.x, the branch Kafka uses.
3.3.0 targets zookeeper 3.5.x, currently in beta and not working with Kafka

It seems curator-test was upgraded to 4.0.0 as part of this commit: https://github.com/charithe/kafka-junit/commit/89bfeed33e50eff677d63747e9527d9d024d0835 Although I'm not sure if there's any reason why it has. 

Bottom line, I believe downgrading to 2.12 is both safer and more sound based on matching the kafka zookeeper client version. It also prevents project onboarding this library from having zookeeper clients in version beta 3.5.x.

I tested the project itself and it passes its own test suite, which is a pretty good indication the project shouldn't break anything https://github.com/charithe/kafka-junit/pull/30. 

I think it's still time to make a good decision for this project to follow the 2.x branch of curator-test. If you don't agree with me that's fine I won't insist :) Hope you understand my point of view

**Comment by charithe** [comment]
It's been a while so I can't remember the reason for the upgrade. My fear is that the 3.x version has been out for a long time and by suddenly downgrading one of the dependencies, I could break existing code that may be accidentally (or, indeed, intentionally) relying on it. As this is a minor dependency conflict with a _supporting_ Kafka library, I don't feel like a downgrade is justified here.

If you're uncomfortable with the dependency versions, feel free to keep your fork up. The code is Apache licensed and any future updates are most likely to be just Kafka version updates anyway.
