### ISSUE TITLE
Transactional producer not working

### ISSUE THREAD

**Issue by shubhamDhoble** [charithe/kafka-junit#35]
I have created a kafka producer(v1.0.0) and tried using transactions. The kafka-junit broker(v4.1.0) is running. The code snippet looks like:

        Properties config = new Properties();
        config.put("transactional.id","id");
        config.put("acks","all");
        KafkaProducer<String, String> producer =
                     broker.createProducer(new StringSerializer(), new StringSerializer(), config);
        System.out.println("producer created");
        producer.initTransactions();
        System.out.println("init transaction");
        producer.send(new ProducerRecord<>(TEST_TOPIC, "key1", "value1"));

This code gets stuck in a loop while executing the statement initTransactions().

**Comment by charithe** [comment]
This is because the default Kafka configuration sets the number of replicas for the transaction topic to 3.  You need to explicitly configure it to require just one replica _before_ the broker is started.

```java
        Properties brokerConf = new Properties();
        brokerConf.put("transaction.state.log.replication.factor", "1");
        brokerConf.put("transaction.state.log.min.isr", "1");
        brokerConf.put("transaction.state.log.num.partitions", "1");
        brokerConf.put("transaction.timeout.ms", "500");

        EphemeralKafkaBroker broker = EphemeralKafkaBroker.create(9092, 2100, brokerConf);
        KafkaHelper helper = KafkaHelper.createFor(broker);

        Properties producerProps = new Properties();
        producerProps.put("transactional.id", "txid");
        producerProps.put("acks", "all");
        KafkaProducer<String, String> producer = helper.createStringProducer(producerProps);
        // transaction code
```

I'll make these settings the default in the next release of the library. Until then, you'll have to write some bootstrap code like above to test transactions.

**Comment by shubhamDhoble** [comment]
Thank you, this solution worked and solved my problem.
