### ISSUE TITLE
When using timeout to simulate "no-message" scenario, other regular test cases stop working 

### ISSUE THREAD

**Issue by jainishan** [charithe/kafka-junit#43]
I posted a question on stackoverflow about the problem i was having when running my entire test suite - https://stackoverflow.com/q/56076971/1029684

Further investigation showed that my test cases would fail when executed after some test cases that use the timeout function in kafkaRule.helper().consumeStrings().get(). I am using the @Rule annotation but still the test case seems to be getting affected by previous runs. I had to do some exclusions in maven to get this lib working. Below is the Maven part and the test cases i have:

POM.xml
```
 <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>3.5.3-beta</version>
        </dependency>

        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.12</artifactId>
            <version>2.1.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>scala-library</artifactId>
                    <groupId>org.scala-lang</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>scala-reflect</artifactId>
                    <groupId>org.scala-lang</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>scala-logging_2.12</artifactId>
                    <groupId>com.typesafe.scala-logging</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>zookeeper</artifactId>
                    <groupId>org.apache.zookeeper</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.github.charithe</groupId>
            <artifactId>kafka-junit</artifactId>
            <version>4.1.3</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <artifactId>kafka_2.12</artifactId>
                    <groupId>org.apache.kafka</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

Jnuit 4 tests
```
public class KafkaTest {
    private static int kafkaBrokerPort = 9000;

    private final String MY_TOPIC = "my-topic";

    @Rule
    public KafkaJunitRule kafkaRule = new KafkaJunitRule(EphemeralKafkaBroker.create(kafkaBrokerPort));

    @Test
    public void B() throws InterruptedException, TimeoutException, ExecutionException {
        // App logic that sends messages to Kafka
        kafkaRule.helper().produceStrings(MY_TOPIC, "a", "b", "c", "d", "e");

        List<String> result = kafkaRule.helper().consumeStrings(MY_TOPIC, 5).get(30, TimeUnit.SECONDS);
        assertEquals(5, result.size());
    }

    @Test
    public void A() throws InterruptedException, ExecutionException {
        // App logic that doesn't send messages to Kafka

        List<String> result = Collections.emptyList();
        try {
            result = kafkaRule.helper().consumeStrings(MY_TOPIC, 1).get(10000, TimeUnit.MILLISECONDS);
        } catch (TimeoutException e) {
            // Do nothing
        }

        assertEquals(0, result.size());
    }
}
```

When i run test A or B individually, they are execute successfully all the time. When i run the whole test suite and if B executed before A, then again everything goes fine. It is only when i run the test suite and B gets executed before A, it fails. 
It has something to do with the timeout thing i implemented. I could not find out any other way to simulate the condition where i check the message was not sent.

**Comment by charithe** [comment]
There's not enough information here for me to give you a good answer. Please provide a minimal test case that reproduces the issue.

**Comment by jainishan** [comment]
Updated the code sample above to include the working test case. When you execute A or B individually, they will pass always. When you run the whole test suite where first A is executed then B, B will always fail.

**Comment by charithe** [comment]
OK, so this is interesting. First of all, `KafkaHelper#consumeStrings` is only good for happy path usage because otherwise the timeout/cancellation of the `Future` would fail to properly close the consumer. (I kind of regret adding those helpers but now it's too late to change the API.) Because the consumer is running in a background thread and has not been cleanly shutdown, it is interfering with the subsequent tests. This is because you have pinned the Kafka rule to use a fixed port -- which allows the zombie consumer to reconnect to the Kafka broker spun up for the next test in the suite.

So, the **hacky** way to make your tests pass is to use a random Kafka port for each test by changing the rule creation to look as follows:

```java
@Rule
public KafkaJunitRule kafkaRule = new KafkaJunitRule(EphemeralKafkaBroker.create());

// If you really need to know he Kafka port, it can be found by calling kafkaRule.helper().kafkaPort()
```

However, the better way (IMO) to write the tests would be as follows:

```java
public class SomeTest {
    private static int kafkaBrokerPort = 9000;

    private final String MY_TOPIC = "my-topic";

    @Rule
    public KafkaJunitRule kafkaRule = new KafkaJunitRule(EphemeralKafkaBroker.create(kafkaBrokerPort)).waitForStartup();

    @Test
    public void A() {
        try (KafkaConsumer<String, String> consumer = kafkaRule.helper().createStringConsumer()) {
            consumer.subscribe(Lists.newArrayList(MY_TOPIC));
            ConsumerRecords<String, String> records = consumer.poll(Duration.ofSeconds(10));
            assertTrue(records.isEmpty());
        } 
    }

    @Test
    public void B() throws InterruptedException, TimeoutException, ExecutionException {
        KafkaHelper helper = kafkaRule.helper();
        helper.produceStrings(MY_TOPIC, "a", "b", "c", "d", "e");
        List<String> result = helper.consumeStrings(MY_TOPIC, 5).get(10, TimeUnit.SECONDS);
        assertEquals(5, result.size());
    }
}
```

**Comment by jainishan** [comment]
Hi,
Thanks for the answer. It worked nicely when i created a separate consumer for each broker. Probably it will help to change the example in the README.md file to not show consumeStrings.

What are your thoughts on testing 'no message' scenarios ? I searched a lot but seems like not everyone implements them. Yet i wanted to try because they seem relevant in my case. Those waiting times drastically increase the test cases run time, but i see no other good way to implement that.
