### ISSUE TITLE
Kafka 2.4

### ISSUE THREAD

**Issue by adriancole** [charithe/kafka-junit#46]
We'll soon get pressure to support Kafka 2.4, so will be helpful to have a compatible release here. cheers.

**Comment by adriancole** [comment]
thanks so much!

**Comment by charithe** [comment]
My computer lied to me. All the tests passed with the version bumped up but I got compilation errors when I tried to release the artifact. Looks like `ZkUtils` is deprecated and needs to be replaced. I am currently travelling so I don't have time to do a major refactor for a few more days. I will leave this open if anybody wants to volunteer to fix it while I am away.

**Comment by charithe** [comment]
4.1.7 has been released.
