### ISSUE TITLE
producerConfig() with DefaultEncoder

### ISSUE THREAD

**Issue by adriancole** [charithe/kafka-junit#5]
It would be nice if there was a quick way to create a producerConfig with the DefaultEncoder as opposed to the StringEncoder. I would use it in zipkin https://github.com/openzipkin/zipkin/pull/476/files

**Comment by charithe** [comment]
Good point. I just released version 1.4 which has a method called  `producerConfigWithDefaultEncoder()` that creates a producer configuration with the default encoder. There's `producerConfigWithStringEncoder()` for Strings and `producerConfig(String encoderClassName)` for any other custom encoders.

**Comment by adriancole** [comment]
Thanks!
