### ISSUE TITLE
Multipartition topic

### ISSUE THREAD

**Issue by mchernyakov** [charithe/kafka-junit#51]
Hello, I have not found how can I create a multipartition topic, using `KafkaJunitRule`. 
Probably I have missed something. Any suggestions?

**Comment by charithe** [comment]
The rule spins up a temporary Kafka broker that you can interact with as usual. The example in the README shows how to obtain information about the broker such as the Zookeeper quorum, broker port etc. You can use that information to create an Admin client and create topics. Keep in mind that it's a single broker so if you use a replication factor or any other setting that requires more than one broker, those operations are likely to fail.

**Comment by mchernyakov** [comment]
Got it, thanks.
