### ISSUE TITLE
Breaking changes from Kafka 2.8.0

### ISSUE THREAD

**Issue by bgeisberger** [charithe/kafka-junit#61]
Unfortunately, this library is not compatible with Kafka 2.8.0
In a recent commit (https://github.com/apache/kafka/commit/8f063c15da51d77a40aa63f110e48c5eeeaf5dfc), KafkaServerStartable got removed, which breaks the EphemeralKafkaBroker.

**Comment by TheKnowles** [comment]
@charithe I opened a pull request for this. I updated to kafka 2.8.0.

**Comment by charithe** [comment]
Brilliant! Thank you.
